# Generated by Django 5.2.9 on 2026-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_pics/'),
        ),
    ]
