# Generated by Django 5.2.9 on 2026-05-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'weekday')},
        ),
    ]
