# Generated by Django 5.2.9 on 2026-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctoravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/doctors'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/patients'),
        ),
    ]
