# Generated by Django 5.2.9 on 2026-05-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
