# Generated by Django 5.2.9 on 2026-05-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctoravailability_unique_together'),
        ('booking', '0002_remove_appointment_slot_delete_timeslot'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, default=datetime.date(2026, 5, 8), null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 10)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.time(20, 10)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='booking_app_doctor__7ada71_idx'),
        ),
    ]
