# Generated by Django 5.2.9 on 2026-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctoravailability_unique_together'),
        ('booking', '0004_alter_appointment_appointment_date'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='valid_appointment_time'),
        ),
    ]
