# Generated by Django 5.2.9 on 2026-05-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment_valid_appointment_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='valid_appointment_time',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='booking_app_doctor__7ada71_idx',
        ),
    ]
