# Generated by Django 5.2.9 on 2026-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_appointment_valid_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/records/'),
        ),
    ]
