# Generated by Django 5.2.9 on 2026-05-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_medicalrecord_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pain_level',
        ),
    ]
