# Generated by Django 5.2.9 on 2026-05-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_appointment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed'), ('RESCHEDULE', 'Reschedule')], default='PENDING', max_length=20),
        ),
    ]
