# Generated by Django 6.0.4 on 2026-05-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Availablity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_availablity', models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'others')], max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('medical_history', models.FileField(blank=True, null=True, upload_to='medical_file/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.CharField(max_length=50)),
                ('fees', models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
