# Generated by Django 6.0.4 on 2026-05-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_availablity_user_alter_hospital_id_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
