# Generated by Django 6.0.4 on 2026-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_timeslot_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pain_level',
            field=models.CharField(blank=True, choices=[('NO PAIN', 'no pain'), ('MILD PAIN', 'mild pain'), ('MODERATE PAIN', 'moderate pain'), ('SEVERE PAIN', 'severe pain'), ('WORST PAIN', 'worst pain')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(),
        ),
    ]
